name: hydrated_state_notifier
description: An extension to the state_notifier library which automatically persists and restores state_notifier states.
version: 2.0.0
homepage: https://github.com/predatorx7/hydrated_state_notifier/tree/main/packages/hydrated_state_notifier

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.3.0
  state_notifier: ^1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
  collection: ^1.15.0
  crypto: ^3.0.0
  freezed_annotation: ^2.4.1
  freezed: ^2.4.7
  json_serializable: ^6.0.0
  json_annotation: ^4.3.0
  mocktail: ^1.0.3
  path: ^1.8.0
  uuid: ^4.3.3
