name: hydrated_state_notifier
description: An extension to the state_notifier library which automatically persists and restores state_notifier states.
version: 1.0.0
homepage: https://github.com/predatorx7/hydrated_state_notifier/tree/main/packages/hydrated_state_notifier

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.17.1
  meta: ^1.3.0
  state_notifier: ^0.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  crypto: ^3.0.0
  freezed_annotation: ^0.15.0
  freezed: ^0.15.0+1
  json_serializable: ^6.0.0
  json_annotation: ^4.3.0
  mocktail: ^0.3.0
  path: ^1.8.0
  uuid: ^3.0.0
