name: hydrated_state_notifier_hive
description: An implementation of HydratedStorage from hydrated_state_notifier library which automatically persists and restores states built on top of hive.
version: 2.0.0
publish_to: "none"
homepage: https://github.com/predatorx7/hydrated_state_notifier/tree/main/packages/hydrated_state_notifier_hive

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  hive: ^2.0.0
  synchronized: ^3.0.0
  meta: ^1.3.0
  hydrated_state_notifier:
    git:
      url: git@github.com:amanxnanda/hydrated_state_notifier.git
      ref: chore/dependency-upgrade
      path: packages/hydrated_state_notifier

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
  collection: ^1.15.0
  crypto: ^3.0.0
  freezed_annotation: ^2.4.1
  freezed: ^2.4.7
  json_serializable: ^6.0.0
  json_annotation: ^4.3.0
  mocktail: ^1.0.3
  path: ^1.8.0
  uuid: ^4.3.3
